require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LessonTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # LessonTemplate. As you add validations to LessonTemplate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lesson_templates as @lesson_templates" do
      lesson_template = LessonTemplate.create! valid_attributes
      get :index
      assigns(:lesson_templates).should eq([lesson_template])
    end
  end

  describe "GET show" do
    it "assigns the requested lesson_template as @lesson_template" do
      lesson_template = LessonTemplate.create! valid_attributes
      get :show, :id => lesson_template.id.to_s
      assigns(:lesson_template).should eq(lesson_template)
    end
  end

  describe "GET new" do
    it "assigns a new lesson_template as @lesson_template" do
      get :new
      assigns(:lesson_template).should be_a_new(LessonTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested lesson_template as @lesson_template" do
      lesson_template = LessonTemplate.create! valid_attributes
      get :edit, :id => lesson_template.id.to_s
      assigns(:lesson_template).should eq(lesson_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LessonTemplate" do
        expect {
          post :create, :lesson_template => valid_attributes
        }.to change(LessonTemplate, :count).by(1)
      end

      it "assigns a newly created lesson_template as @lesson_template" do
        post :create, :lesson_template => valid_attributes
        assigns(:lesson_template).should be_a(LessonTemplate)
        assigns(:lesson_template).should be_persisted
      end

      it "redirects to the created lesson_template" do
        post :create, :lesson_template => valid_attributes
        response.should redirect_to(LessonTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lesson_template as @lesson_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonTemplate.any_instance.stub(:save).and_return(false)
        post :create, :lesson_template => {}
        assigns(:lesson_template).should be_a_new(LessonTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonTemplate.any_instance.stub(:save).and_return(false)
        post :create, :lesson_template => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lesson_template" do
        lesson_template = LessonTemplate.create! valid_attributes
        # Assuming there are no other lesson_templates in the database, this
        # specifies that the LessonTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LessonTemplate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lesson_template.id, :lesson_template => {'these' => 'params'}
      end

      it "assigns the requested lesson_template as @lesson_template" do
        lesson_template = LessonTemplate.create! valid_attributes
        put :update, :id => lesson_template.id, :lesson_template => valid_attributes
        assigns(:lesson_template).should eq(lesson_template)
      end

      it "redirects to the lesson_template" do
        lesson_template = LessonTemplate.create! valid_attributes
        put :update, :id => lesson_template.id, :lesson_template => valid_attributes
        response.should redirect_to(lesson_template)
      end
    end

    describe "with invalid params" do
      it "assigns the lesson_template as @lesson_template" do
        lesson_template = LessonTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => lesson_template.id.to_s, :lesson_template => {}
        assigns(:lesson_template).should eq(lesson_template)
      end

      it "re-renders the 'edit' template" do
        lesson_template = LessonTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => lesson_template.id.to_s, :lesson_template => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lesson_template" do
      lesson_template = LessonTemplate.create! valid_attributes
      expect {
        delete :destroy, :id => lesson_template.id.to_s
      }.to change(LessonTemplate, :count).by(-1)
    end

    it "redirects to the lesson_templates list" do
      lesson_template = LessonTemplate.create! valid_attributes
      delete :destroy, :id => lesson_template.id.to_s
      response.should redirect_to(lesson_templates_url)
    end
  end

end
